development:
	adapter: mysql
	encoding: utf8
	reconnect: false
	database: test
	pool: 5
	username: intranet
	password: intranet
	shost: 192.168.1.2

test:
	adapter: mysql
	encoding: utf8
	reconnect: false
	database: test
	pool: 5
	username: intranet
	password: intranet
	shost: 192.168.1.2

production:
	adapter: mysql
	encoding: utf8
	reconnect: false
	database: test
	pool: 5
	username: intranet
	password: intranet
	shost: 192.168.1.2
