development:
	adapter: mysql2
	encoding: utf8
	reconnect: false
	database: intranet
	pool: 5
	username: intranet
	password: intranet
	shost: 192.168.1.2

test:
	adapter: mysql2
	encoding: utf8
	reconnect: false
	database: intranet
	pool: 5
	username: intranet
	password: intranet
	shost: 192.168.1.2

production:
	adapter: mysql2
	encoding: utf8
	reconnect: false
	database: intranet
	pool: 5
	username: intranet
	password: intranet
	shost: 192.168.1.2
